const assetMapping = {
    mainLogo: process.env.PUBLIC_URL + "/assets/website/mainlogo.png",
    gameplayVideo: process.env.PUBLIC_URL + "/assets/website/gameplay6.mp4",
    chatJumpTitle: process.env.PUBLIC_URL + "/assets/website/chatjumptitle.svg",
    cloud1: process.env.PUBLIC_URL + "/assets/game/sprites/environment/cloud1.png",
    cloud2: process.env.PUBLIC_URL + "/assets/game/sprites/environment/cloud2.png",
    cloud3: process.env.PUBLIC_URL + "/assets/game/sprites/environment/cloud3.png",
    yellowArrow: process.env.PUBLIC_URL + "/assets/website/yellowarrow.svg",
    chestWithCoins: process.env.PUBLIC_URL + "/assets/website/chestwithcoins.svg",
    sampleWords: process.env.PUBLIC_URL + "/assets/website/samplewords.svg",
    highScoreGuy: process.env.PUBLIC_URL + "/assets/website/highscoreguy.svg",
    ground: process.env.PUBLIC_URL + "/assets/website/ground.png",
    dirt: process.env.PUBLIC_URL + "/assets/website/dirt.png",
    day9Video: process.env.PUBLIC_URL + "/assets/website/day9video.mp4",
    day9Logo: process.env.PUBLIC_URL + "/assets/website/day9logo.svg",
    mascot: process.env.PUBLIC_URL + "/assets/website/mascot.svg",
    quoteMark: process.env.PUBLIC_URL + "/assets/website/quotemark.svg",
    singleJumper: process.env.PUBLIC_URL + "/assets/website/singlejumper.png",
    coins: process.env.PUBLIC_URL + "/assets/website/coins.png",
    chest: process.env.PUBLIC_URL + "/assets/website/chestsingle.png",
    star: process.env.PUBLIC_URL + "/assets/website/star.png",
    brian: process.env.PUBLIC_URL + "/assets/website/brian.jpeg",
    hong: process.env.PUBLIC_URL + "/assets/website/hong.jpeg",
    lawrence: process.env.PUBLIC_URL + "/assets/website/lawrence.jpeg",
    guest: process.env.PUBLIC_URL + "/assets/website/guest.svg",
    twitchLogo: process.env.PUBLIC_URL + "/assets/website/twitchglitchwhite.svg",
    playerIcon: process.env.PUBLIC_URL + "/assets/website/player.svg",
};

export default assetMapping;
