const assetMapping = {
    mainLogo: process.env.PUBLIC_URL + "/assets/mainlogo.png",
    gameplayVideo: process.env.PUBLIC_URL + "/assets/gameplay6.mp4",
    chatJumpTitle: process.env.PUBLIC_URL + "/assets/chatjumptitle.svg",
    cloud1: process.env.PUBLIC_URL + "/assets/cloud1.png",
    cloud2: process.env.PUBLIC_URL + "/assets/cloud2.png",
    cloud3: process.env.PUBLIC_URL + "/assets/cloud3.png",
    yellowArrow: process.env.PUBLIC_URL + "/assets/yellowarrow.svg",
    chestWithCoins: process.env.PUBLIC_URL + "/assets/chestwithcoins.svg",
    sampleWords: process.env.PUBLIC_URL + "/assets/samplewords.svg",
    highScoreGuy: process.env.PUBLIC_URL + "/assets/highscoreguy.svg",
    ground: process.env.PUBLIC_URL + "/assets/ground.png",
    dirt: process.env.PUBLIC_URL + "/assets/dirt.png",
    day9Video: process.env.PUBLIC_URL + "/assets/day9video.mp4",
    day9Logo: process.env.PUBLIC_URL + "/assets/day9logo.svg",
    mascot: process.env.PUBLIC_URL + "/assets/mascot.svg",
    quoteMark: process.env.PUBLIC_URL + "/assets/quotemark.svg",
    singleJumper: process.env.PUBLIC_URL + "/assets/singlejumper.png",
    coins: process.env.PUBLIC_URL + "/assets/coins.png",
    chest: process.env.PUBLIC_URL + "/assets/chestsingle.png",
    star: process.env.PUBLIC_URL + "/assets/star.png",
    brian: process.env.PUBLIC_URL + "/assets/brian.jpeg",
    hong: process.env.PUBLIC_URL + "/assets/hong.jpeg",
    lawrence: process.env.PUBLIC_URL + "/assets/lawrence.jpeg",
    guest: process.env.PUBLIC_URL + "/assets/guest.svg",
    twitchLogo: process.env.PUBLIC_URL + "/assets/twitchglitchwhite.svg",
    playerIcon: process.env.PUBLIC_URL + "/assets/player.svg",
};

export default assetMapping;
